### ISSUE TITLE
editorconfigにluaを追記

### ISSUE THREAD

**Issue by satler-git** [satler-git/dotfiles#70]
styluaにあわせる

**Comment by satler-git** [comment]
```toml
[*.lua]
indent_style = space
indent_size = 4
```
